// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugnieydusghsnugktgtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnbmlleWR1c2doc251Z2t0Z3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzI3MzQsImV4cCI6MjA2Mzk0ODczNH0.4UZHNWCrDAmoBHoqH6IxnYlE5ElI8AYDhYNCBZyNbjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);